#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh --forest

bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap           10
bspc config split_ratio          0.50

xsetroot -cursor_name left_ptr

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# 1st desktop
bspc rule -a Alacritty desktop='^1' follow=on focus=on

# 2nd desktop
declare -a web=(firefox discord)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# 3rd desktop
bspc rule -a Pcmanfm desktop='^3' follow=on focus=on

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'


bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Pcmanfm state=floating follow=on focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
