#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh --forest

# initialize betterlockscreen
betterlockscreen -u /usr/share/backgrounds/archlinux/small.png

bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap           10
bspc config split_ratio          0.50

bspc config focused_border_color "#81A1C1"
bspc config normal_border_color "#2E3440"
bspc config active_border_color "#B48EAD"
bspc config border_width 3

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# 1st desktop
bspc rule -a Alacritty desktop='^1' follow=on focus=on

# 2nd desktop
declare -a web=(firefox discord)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# 3rd desktop
bspc rule -a Pcmanfm desktop='^3' follow=on focus=on

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'


bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Pcmanfm state=floating follow=on focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


## Autostart

# Kill if already running
killall -9 sxhkd dunst xfce4-power-manager

# Launch notification daemon
dunst \
-geom "280x50-10+38" -frame_width "1" -font "Source Code Pro Medium 5" \
-lb "#2E3440" -lf "#D8DEE9" -lfr "#81A1C1" \
-nb "#2E3440" -nf "#D8DEE9" -nfr "#81A1C1" \
-cb "#2E3440" -cf "#BF616A" -cfr "#BF616A" &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Launch keybindings daemon
sxhkd &

# fix pointer
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg

# Enable power management
xfce4-power-manager &

# Start mpd
exec mpd &
