#!/usr/bin/bash

# Examples
# Intel : intel_backlight
# AMD   : amdgpu_bl0

STYLE=`cat $HOME/.config/dunst/sid`
CARD=`ls /sys/class/backlight | head -n 1`

if [[ "$CARD" == *"intel_"* ]]; then
	if [[ "$STYLE" == "Light" ]]; then
		xbacklight -inc 10 && dunstify -u low --replace=69 -i /usr/share/icons/Archcraft/actions/24/whitebalance.svg "Brightness Inc : $(backlight)%"
	else
		xbacklight -inc 10 && dunstify -u low --replace=69 -i /usr/share/icons/Archcraft-Dark/actions/24/whitebalance.svg "Brightness Inc : $(backlight)%"
	fi
else
	if [[ "$STYLE" == "Light" ]]; then
		blight -d "$CARD" set +5% && dunstify -u low --replace=69 -i /usr/share/icons/Archcraft/actions/24/whitebalance.svg "Brightness Inc : $(backlight)%"
	else
		blight -d "$CARD" set +5% && dunstify -u low --replace=69 -i /usr/share/icons/Archcraft-Dark/actions/24/whitebalance.svg "Brightness Inc : $(backlight)%"
	fi
fi
