#!/bin/bash

STYLE=$(cat $HOME/.config/dunst/sid)

if [[ "$STYLE" == "Light" ]]; then
	amixer -Mq set Master,0 5%- unmute && dunstify -u low --replace=69 -i /usr/share/icons/Archcraft/status/24/audio-volume-medium.svg "Volume Down : $(volume)%"
else
	amixer -Mq set Master,0 5%- unmute && dunstify -u low --replace=69 -i /usr/share/icons/Archcraft-Dark/status/24/audio-volume-medium.svg "Volume Down : $(volume)%"
fi
