#!/bin/bash

STYLE=$(cat $HOME/.config/dunst/sid)

if [[ "$STYLE" == "Light" ]]; then
	amixer -Mq set Master,0 5%- unmute && dunstify -u low --replace=69 -i /usr/share/icons/Papirus-Light/symbolic/status/audio-volume-medium-symbolic.svg "Volume Down : $(volume)%"
else
	amixer -Mq set Master,0 5%- unmute && dunstify -u low --replace=69 -i /usr/share/icons/Papirus-Dark/symbolic/status/audio-volume-medium-symbolic.svg "Volume Down : $(volume)%"
fi
